### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by AlexeyAndKartashov**
Can you publish this package on npm with this pull request with updated version please?

### CODE REVIEW

**Comment by koskimas** [comment]
Why?

**Comment by koskimas** [comment]
Oh, because of your previous PR's probably? Will do.

**Comment by koskimas** [comment]
1.1.2 published.

**Comment by AlexeyAndKartashov** [comment]
> because of your previous PR's probably?

Exactly!
Thank you very much!

**Pull request merged**
